import os, sys
def resource_path(relative_path):
    try:
        base_path = sys._MEIPASS
    except AttributeError:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_Root(object):
    def setupUi(self, Root):
        Root.setObjectName("Root")
        Root.resize(1156, 816)
        Root.setMinimumSize(QtCore.QSize(1156, 816))
        Root.setMaximumSize(QtCore.QSize(1156, 816))
        self.image_bg = QtWidgets.QLabel(Root)
        self.image_bg.setGeometry(QtCore.QRect(0, 0, 1161, 821))
        self.image_bg.setText("")
        self.image_bg.setPixmap(QtGui.QPixmap(resource_path("images/Ui.jpg")))
        self.image_bg.setObjectName("image_bg")
        self.start_area = QtWidgets.QMdiArea(Root)
        self.start_area.setGeometry(QtCore.QRect(162, 217, 181, 91))
        brush = QtGui.QBrush(QtGui.QColor(158, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.start_area.setBackground(brush)
        self.start_area.setObjectName("start_area")
        self.start_length_label = QtWidgets.QLabel(Root)
        self.start_length_label.setGeometry(QtCore.QRect(171, 216, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.start_length_label.setFont(font)
        self.start_length_label.setObjectName("start_length_label")
        self.start_pitch_label = QtWidgets.QLabel(Root)
        self.start_pitch_label.setGeometry(QtCore.QRect(170, 262, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.start_pitch_label.setFont(font)
        self.start_pitch_label.setObjectName("start_pitch_label")
        self.start_length_value = QtWidgets.QDoubleSpinBox(Root)
        self.start_length_value.setGeometry(QtCore.QRect(227, 225, 109, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.start_length_value.setFont(font)
        self.start_length_value.setMinimum(1.0)
        self.start_length_value.setMaximum(1e+81)
        self.start_length_value.setObjectName("start_length_value")
        self.start_pitch_value = QtWidgets.QDoubleSpinBox(Root)
        self.start_pitch_value.setGeometry(QtCore.QRect(228, 269, 108, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.start_pitch_value.setFont(font)
        self.start_pitch_value.setMinimum(1.0)
        self.start_pitch_value.setMaximum(1e+81)
        self.start_pitch_value.setObjectName("start_pitch_value")
        self.end_area = QtWidgets.QMdiArea(Root)
        self.end_area.setGeometry(QtCore.QRect(830, 217, 181, 91))
        brush = QtGui.QBrush(QtGui.QColor(158, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.end_area.setBackground(brush)
        self.end_area.setObjectName("end_area")
        self.end_length_label = QtWidgets.QLabel(Root)
        self.end_length_label.setGeometry(QtCore.QRect(840, 217, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.end_length_label.setFont(font)
        self.end_length_label.setObjectName("end_length_label")
        self.end_pitch_label = QtWidgets.QLabel(Root)
        self.end_pitch_label.setGeometry(QtCore.QRect(838, 261, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.end_pitch_label.setFont(font)
        self.end_pitch_label.setObjectName("end_pitch_label")
        self.end_length_value = QtWidgets.QDoubleSpinBox(Root)
        self.end_length_value.setGeometry(QtCore.QRect(896, 226, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.end_length_value.setFont(font)
        self.end_length_value.setMinimum(1.0)
        self.end_length_value.setMaximum(1e+81)
        self.end_length_value.setObjectName("end_length_value")
        self.end_pitch_value = QtWidgets.QDoubleSpinBox(Root)
        self.end_pitch_value.setGeometry(QtCore.QRect(896, 269, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.end_pitch_value.setFont(font)
        self.end_pitch_value.setMinimum(1.0)
        self.end_pitch_value.setMaximum(1e+81)
        self.end_pitch_value.setObjectName("end_pitch_value")
        self.feed_area = QtWidgets.QMdiArea(Root)
        self.feed_area.setGeometry(QtCore.QRect(156, 56, 190, 53))
        brush = QtGui.QBrush(QtGui.QColor(158, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.feed_area.setBackground(brush)
        self.feed_area.setObjectName("feed_area")
        self.feed_label = QtWidgets.QLabel(Root)
        self.feed_label.setGeometry(QtCore.QRect(163, 61, 70, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.feed_label.setFont(font)
        self.feed_label.setObjectName("feed_label")
        self.feed_value = QtWidgets.QSpinBox(Root)
        self.feed_value.setGeometry(QtCore.QRect(236, 67, 106, 33))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.feed_value.setFont(font)
        self.feed_value.setMaximum(999999999)
        self.feed_value.setObjectName("feed_value")
        self.speed_area = QtWidgets.QMdiArea(Root)
        self.speed_area.setGeometry(QtCore.QRect(823, 56, 196, 53))
        brush = QtGui.QBrush(QtGui.QColor(158, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.speed_area.setBackground(brush)
        self.speed_area.setObjectName("speed_area")
        self.speed_label = QtWidgets.QLabel(Root)
        self.speed_label.setGeometry(QtCore.QRect(830, 60, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.speed_label.setFont(font)
        self.speed_label.setObjectName("speed_label")
        self.speed_value = QtWidgets.QSpinBox(Root)
        self.speed_value.setGeometry(QtCore.QRect(917, 67, 99, 33))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.speed_value.setFont(font)
        self.speed_value.setMaximum(999999999)
        self.speed_value.setObjectName("speed_value")
        self.total_length_area = QtWidgets.QMdiArea(Root)
        self.total_length_area.setGeometry(QtCore.QRect(500, 138, 181, 50))
        brush = QtGui.QBrush(QtGui.QColor(158, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.total_length_area.setBackground(brush)
        self.total_length_area.setObjectName("total_length_area")
        self.total_length_label = QtWidgets.QLabel(Root)
        self.total_length_label.setGeometry(QtCore.QRect(510, 140, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.total_length_label.setFont(font)
        self.total_length_label.setObjectName("total_length_label")
        self.total_length_value = QtWidgets.QDoubleSpinBox(Root)
        self.total_length_value.setGeometry(QtCore.QRect(550, 148, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.total_length_value.setFont(font)
        self.total_length_value.setMinimum(1.0)
        self.total_length_value.setMaximum(1e+81)
        self.total_length_value.setObjectName("total_length_value")
        self.helix_length_area = QtWidgets.QMdiArea(Root)
        self.helix_length_area.setGeometry(QtCore.QRect(500, 220, 181, 81))
        brush = QtGui.QBrush(QtGui.QColor(158, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.helix_length_area.setBackground(brush)
        self.helix_length_area.setObjectName("helix_length_area")
        self.sign_area = QtWidgets.QMdiArea(Root)
        self.sign_area.setGeometry(QtCore.QRect(536, 320, 111, 71))
        brush = QtGui.QBrush(QtGui.QColor(158, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.sign_area.setBackground(brush)
        self.sign_area.setObjectName("sign_area")
        self.isRTL = QtWidgets.QRadioButton(Root)
        self.isRTL.setGeometry(QtCore.QRect(544, 330, 95, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.isRTL.setFont(font)
        self.isRTL.setIconSize(QtCore.QSize(200, 200))
        self.isRTL.setChecked(False)
        self.isRTL.setAutoRepeat(True)
        self.isRTL.setAutoRepeatDelay(300)
        self.isRTL.setObjectName("isRTL")
        self.isLTR = QtWidgets.QRadioButton(Root)
        self.isLTR.setGeometry(QtCore.QRect(544, 360, 95, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.isLTR.setFont(font)
        self.isLTR.setIconSize(QtCore.QSize(200, 200))
        self.isLTR.setChecked(True)
        self.isLTR.setAutoRepeat(True)
        self.isLTR.setAutoRepeatDelay(300)
        self.isLTR.setObjectName("isLTR")
        self.stop_area = QtWidgets.QMdiArea(Root)
        self.stop_area.setGeometry(QtCore.QRect(542, 412, 101, 41))
        brush = QtGui.QBrush(QtGui.QColor(158, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.stop_area.setBackground(brush)
        self.stop_area.setObjectName("stop_area")
        self.isStop = QtWidgets.QCheckBox(Root)
        self.isStop.setGeometry(QtCore.QRect(549, 410, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.isStop.setFont(font)
        self.isStop.setObjectName("isStop")
        self.btn_input = QtWidgets.QPushButton(Root)
        self.btn_input.setGeometry(QtCore.QRect(871, 670, 161, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input.setFont(font)
        self.btn_input.setObjectName("btn_input")
        self.btn_export = QtWidgets.QPushButton(Root)
        self.btn_export.setGeometry(QtCore.QRect(140, 670, 161, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_export.setFont(font)
        self.btn_export.setObjectName("btn_export")
        self.progressBar = QtWidgets.QProgressBar(Root)
        self.progressBar.setGeometry(QtCore.QRect(480, 710, 251, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.Helix_label = QtWidgets.QLabel(Root)
        self.Helix_label.setGeometry(QtCore.QRect(510, 235, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.Helix_label.setFont(font)
        self.Helix_label.setObjectName("Helix_label")

        self.retranslateUi(Root)
        QtCore.QMetaObject.connectSlotsByName(Root)

    def retranslateUi(self, Root):
        _translate = QtCore.QCoreApplication.translate
        Root.setWindowTitle(_translate("Root", "HelixGenerator"))
        self.start_length_label.setText(_translate("Root", "L1 :"))
        self.start_pitch_label.setText(_translate("Root", "P1 :"))
        self.end_length_label.setText(_translate("Root", "L2 :"))
        self.end_pitch_label.setText(_translate("Root", "P2 :"))
        self.feed_label.setText(_translate("Root", "Feed :"))
        self.speed_label.setText(_translate("Root", "Speed :"))
        self.total_length_label.setText(_translate("Root", "L :"))
        self.isRTL.setText(_translate("Root", "RIGHT"))
        self.isLTR.setText(_translate("Root", "LEFT"))
        self.isStop.setText(_translate("Root", "M00"))
        self.btn_input.setText(_translate("Root", "Input"))
        self.btn_export.setText(_translate("Root", "Export"))
        self.Helix_label.setText(_translate("Root", "0"))
